### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getTime')

### ISSUE THREAD

**Issue by Deleplace** [firebase/superstatic#468] opened 2024-05-16 22:49 UTC
Hello, thank you for the nice static web server.

I reported [this bug in firebase-tools](https://github.com/firebase/firebase-tools/issues/7173) (firebase-cli) and I'm not sure of the root cause, but the error stacktrace involved [this line of superstatic](https://github.com/firebase/superstatic/blob/master/src/providers/fs.ts#L110) dereferencing an fs stats time object which happened to be `undefined`.

We (2 people) could reproduce this in macOS and Linux when using Node 22.

However, the bug seems to not occur when using Node 20.

I'm using superstatic 9.0.3 (as found in my system at `/home/linuxbrew/.linuxbrew/Cellar/firebase-cli/13.8.3/libexec/lib/node_modules/firebase-tools/node_modules/superstatic/package.json`).

**Comment by Deleplace** [comment] 2024-05-16 22:54
The superstatic package.json says
```
"engines": {
    "node": "18 || 20"
}
```

so it might be a misconfiguration in firebase-tools to accept Node 22.

**Comment by gkalpak** [comment] 2024-06-13 22:16
For anyone wondering, I believe the problem is that the `mtime` property is now initially defined on the `Stat` prototype (instead of on the `Stat` instance itself (due to https://github.com/nodejs/node/pull/50908).

As a result, the spread operator [here][1] does not include the `mtime` key (since the spread operator does not consider enumerable properties on the prototype).

[1]: https://github.com/firebase/superstatic/blob/72817719d4011df1d1a4e18084b01200130fc2e3/src/providers/fs.ts#L35

**Comment by bkendall** [comment] 2024-11-13 16:57
Fixed by https://github.com/firebase/superstatic/pull/484 - published in `9.1.0`

**Closed by bkendall** 2024-11-13 16:57 UTC
